### ISSUE TITLE
运行前端报错, 数据库里没有记录

### ISSUE THREAD

**Issue by yangrudan** [aprilmadaha/pingmesh#4]
前端运行报错如下:
![image](https://github.com/aprilmadaha/pingmesh/assets/66586788/b39ac29d-568e-4ff0-b8eb-45e0d367c30d)
数据库没有记录:
![image](https://github.com/aprilmadaha/pingmesh/assets/66586788/0e1a8812-7fa9-4d1e-b3e3-91d3e0da7299)
同时我在服务器登录时, 进程还会退出:
![image](https://github.com/aprilmadaha/pingmesh/assets/66586788/00575b40-a003-45f1-a1e8-126280e0f10a)

**Comment by aprilmadaha** [comment]
1、先导入下数据库结构体，2、前端指向数据库也的改成你本地的 ，3、clinet源码里面的指向也该下。
